In [ ]:
#Que 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#Ans. #NumPy is a powerful, well-optimized, free open-source library for the Python programming language, adding support for large, multi-dimensional arrays (also called matrices or
#tensors). NumPy also comes equipped #with a collection of high-level mathematical functions to work in conjunction with these arrays. These include basic linear algebra, random
#simulation, Fourier transforms, trigonometric operations, and statistical #Xoperations.
#NumPy stands for ‘numerical Python’, and builds on the early work of the Numeric and Numarray libraries with the goal to give fast numeric computation to Python.
#Today NumPy has numerous contributors and is sponsored by NumFOCUS.

#A multidimensional array is a central data structure of a NumPy library, and generically represents a grid of values. NumPy’s ndarray, a homogeneous n-dimensional array object,
#describes a collection of elements or #items of a similar type. Within these ndarrays, each item comprises the same size memory block and each block is identified the same way.
#This enables efficient, fast, and easy manipulation of data for scientific #computing.

#NumPy array operations are faster than Python Lists because NumPy arrays are compilations of similar data types and are packed densely in memory. By contrast, a Python List can have varying data types, placing additional constraints on the system while performing computation upon them.

#Benefits of NumPy

#Important benefits and properties of NumPy include:

#NumPy’s ndarray computing concepts are at the core of the scientific Python and PyData ecosystems.
#XNumPy provides a Python front-end for highly optimized C functions allowing for a simple Python interface with the speed of compiled code.
#NumPy’s powerful N-dimensional array object integrates with a wide variety of libraries.
#NumPy arrays can execute advanced mathematical operations with large data sets more efficiently and with less code than when using Python’s built-in lists. This is critical for scientific computing sequence, where size and speed are vital.


In [1]:
#Que .2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#Ans. #Difference between np.average() and np.mean()
#Many more arguments, such as dtype, out, where, and others, are available in the np.mean() method that is not accessible in the np.average() function.
#If the weights option is specified, the np.average() function may compute a weighted mean, but np.mean() cannot.
#Since np.average does not take into consideration boolean masks, it will compute the average over the entire collection of data. While the np.mean() method takes into account
#boolean masks, compute the mean #solely across unmasked data.
#You've now seen the key differences between the np.average() and np.mean() functions. You may have noticed that if the weights are not supplied for np.average(),
#it acts similarly to np.mean(); you may be asking #why you would ever use np.mean(). Let us try to answer this question in the following part.

In [2]:
 #Que 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

 #Ans. #Some of the most frequent methods for reversing a numpy array are as follows:
#Utilizing the len() with Loops.
#Using the list slicing technique.
#Using the flip() function.
#Using the reverse() function.
#Using the flipud() function.
#Using the fliplr() function.

#Using flip() function to Reverse a Numpy array


import numpy as np

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# using shortcut method to reverse
res = np.flip(ini_array)

# printing result
print("final array", str(res))


final array [5 4 6 3 2 1]


In [3]:
#Using the list slicing method to reverse a Numpy array

import numpy as np

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# printing initial ini_array
print("initial array", str(ini_array))

# printing type of ini_array
print("type of ini_array", type(ini_array))

# using shortcut method to reverse
res = ini_array[::-1]

# printing result
print("final array", str(res))



initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]


In [ ]:
#Que.4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#Ans. You can check the type of data present in the NumPy array using the '. dtype' attribute. The data type of array 'arr' is 'int' (integer).
#XHere, '32' is related to memory allocation.


#Data types are crucial in programming because they help to enforce code reliability and efficiency. They allow the compiler to allocate the right amount of memory for the data and perform the correct operations on it. Understanding data types and their
#Xuses can lead to more robust and effective code.
#Data types affect memory usage by determining the amount of memory allocated for storing values. For example, an integer typically
#uses less memory than a floating-point number.


In [ ]:
#Que 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative
#integers #Xthat specify the sizes of each dimension.
#The type of items in the array is specified by a separate data-type object (dtype), one of which is associated with each ndarray.
#As with other container objects in Python, the contents of an ndarray can be accessed and modified by indexing or slicing the array (using, for example, N integers), and
#via the methods and attributes of the ndarray.


#The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only
#contain strings and no other data types, but #a Python list can contain a mixture of strings, numbers, booleans and other objects.

#Python Lists vs Arrays: How to Create Python Lists and Arrays
#A list in Python is simply a collection of objects. These objects can be integers, floating point numbers, strings, boolean values or even other data structures like dictionaries.
#An array, specifically a Python NumPy array, is similar to a Python list. The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects.
#Both lists and NumPy arrays have a wide array of built-in methods for performing a variety of tasks including sorting, finding min/max, truncating, appending, concatenating and much more.


In [ ]:
#Que.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations ?

#Ans. The benefits of using NumPy over traditional lists in Python -

#1 .Speed Boost - NumPy arrays provide a significant speed advantage over traditional lists. This is because NumPy is built in C and uses optimized, pre-compiled code for numerical
#operations. This allows for #vectorization, which means operations are applied to all elements in an array without the need for explicit loops in Python. This not only simplifies
#your code but also accelerates execution, as vectorized operations #are inherently faster than their looped counterparts in high-level languages like Python.

#2. Memory Usage -When it comes to memory efficiency, NumPy arrays are far superior to traditional lists. Each item in a NumPy array is of the same data type, requiring less
##memory overhead compared to Python #lists where each element can be of a different type. Furthermore, NumPy arrays are stored contiguously in memory, which enhances performance by
#allowing for efficient access and manipulation of data, particularly #beneficial when handling large datasets.

# 3 Advanced Functions - NumPy comes with a plethora of built-in functions for performing complex mathematical operations, which are not only faster but also more reliable than
#writing your own functions from #scratch. These functions cover a wide range of data science needs, from linear algebra to statistical operations. The convenience and efficiency
#of having these advanced functions at your fingertips can greatly #accelerate your data analysis workflows.

#4. Multidimensional Data - Traditional Python lists are not optimized for multidimensional data operations. NumPy, however, excels in handling such data structures with its
#multidimensional array (ndarray) support. #This allows you to easily perform operations on data across multiple dimensions without the complexity and overhead of nested loops,
#simplifying the manipulation and analysis of complex datasets often #encountered in data science.

In [10]:
#Que 7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#Ans. vstack and hstack
#Suppose you have a 3×3

#array to which you wish to add a row or column. Adding a row is easy with np.vstack:

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.vstack( (a, np.array((2,2,2))) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [13]:
#Adding a column requires a bit more work, however. You can't use np.hstack directly:

a = np.ones((3, 3))
np.hstack( (a, np.array((2,2,2))) )    #in tis way it will throw error


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [14]:
#We can't simply transpose our new row, either, because it's a one-dimensional array and its transpose is the same shape as the original. So we need to reshape it first:


a = np.ones((3, 3))
b = np.array((2,2,2)).reshape(3,1)

In [15]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b

array([[2],
       [2],
       [2]])

In [17]:
np.hstack((a, b))

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [18]:
#Que.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dime?

#Ans. Python numpy.flip() Vs numpy.fliplr() functions

# The numpy.flip() function reverses the order of elements in an array along the given axis, whereas, the numpy.fliplr() function reverses the order of elements along axis 1 (left/right).

#numpy.flip() function
#In NumPy, the numpy.flip() function is used to reverse the order of elements in an array along the given axis. Here, the shape of the array is preserved, but the elements are reordered. It takes a specified axis or axes #as a parameter along which to flip over the order of elements.

#Below is the syntax of numpy.flip() function:

# Python Program illustrating
# numpy.flip() method

import numpy as geek

array = geek.arange(8).reshape((2,2,2))
print("Original array : \n", array)

print("Flipped array : \n", geek.flip(array, 0))




Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Flipped array : 
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


In [19]:
#numpy.fliplr() in Python

# Python Program illustrating
# numpy.fliplr() method

import numpy as geek

array = geek.arange(8).reshape((2,2,2))
print("Original array : \n", array)

# fliplr : means flip left-right
print("\nFlipped array left-right : \n", geek.fliplr(array))


Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array left-right : 
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


In [21]:
#Que.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#Ans. #numpy. array_split() s plitting into equal or nearly equal sub-arrays or is similar to numpy. split(), but it allows for uneven splitting of arrays.
#This is useful when the array cannot be evenly divided by the specified #number of splits.


#Array splitting in NumPy is like a slice of cake. Think of each element in a NumPy array as a slice of cake. Splitting divides this “cake” into smaller “slices” (sub-arrays), often along specific dimensions or based on #certain criteria. We can split horizontally, vertically, or even diagonally depending on our needs.

#The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions. These functions are particularly useful when working with one-dimensional arrays, #matrices, or high-dimensional datasets. NumPy’s array-splitting capabilities are crucial for enhancing the efficiency and flexibility of data processing workflows.

#Key concepts and terminology
#Here are some important terms to understand when splitting arrays:

#Axis: The dimension along which the array is split (e.g., rows, columns, depth).
#Sub-arrays: The smaller arrays resulting from the split.
#Splitting methods: Different functions in NumPy for splitting arrays (e.g., np.split(), np.vsplit(), np.hsplit(), etc.).
#Equal vs. Unequal splits: Whether the sub-arrays have the same size or no


import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)




[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
 #Que 10 .  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#Ans. The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across #the larger one, ensuring that they have compatible shapes for these operations.
#Broadcasting is not limited to two arrays; it can be applied over multiple arrays as well.
#In this article, we will learn about broadcast over multiple arrays in the NumPy extension in Python.

#Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language.
#It does this without making needless copies of data which leads to efficient algorithm implementations. But broadcasting over multiple arrays in NumPy extension can raise cases where broadcasting is a bad idea #because it leads to inefficient use of memory that slows down the computation.
#The resulting array returned after broadcasting will have the same number of dimensions as the array with the greatest number of dimensions.

#Let’s assume that we have a large data set, each data is a list of parameters. In Numpy, we have a 2-D array, where each row is data and the number of rows is the size of the data set. Suppose we want to apply some #sort of scaling to all these data every parameter gets its scaling factor or say every parameter is multiplied by some factor.
#Just to have a clear understanding, let’s count calories in foods using a macro-nutrient breakdown. Roughly put, the caloric parts of food are made of fats (9 calories per gram), protein (4 CPG), and carbs (4 CPG).
#So if we list some foods (our data), and for each food list its macro-nutrient breakdown (parameters), we can then multiply each nutrient by its caloric value (apply scaling) to compute the caloric breakdown of every food item.



In [22]:
#practilce question|

In [23]:
#Que.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

#Ans 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

# Interchange rows and columns (transpose)
transposed_array = array.transpose()
print("\nTransposed array:")
print(transposed_array)


Original array:
[[69  2 68]
 [53 94 30]
 [35 77 95]]

Transposed array:
[[69 53 35]
 [ 2 94 77]
 [68 30 95]]


In [24]:
#Que 2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

#Ans. import numpy as np
arr = np.arange(10)


In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr_2x5 = arr.reshape(2, 5)

In [29]:
arr_2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
arr_5x2 = arr.reshape(5, 2)

In [31]:
arr_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
#Que 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array ?

#Ans.
import numpy as np
random_array = np.random.rand(4, 4)
padded_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

In [34]:
random_array

array([[0.28137017, 0.81647607, 0.01331366, 0.45609035],
       [0.60494895, 0.07680853, 0.87964182, 0.35089739],
       [0.00630232, 0.80719855, 0.73214285, 0.26007963],
       [0.39144015, 0.34931014, 0.65148011, 0.23251304]])

In [35]:
padded_array

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.28137017, 0.81647607, 0.01331366, 0.45609035,
        0.        ],
       [0.        , 0.60494895, 0.07680853, 0.87964182, 0.35089739,
        0.        ],
       [0.        , 0.00630232, 0.80719855, 0.73214285, 0.26007963,
        0.        ],
       [0.        , 0.39144015, 0.34931014, 0.65148011, 0.23251304,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [36]:
#Que 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.?

#Ans. import numpy as np
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [38]:
#Que 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.?

#Ans.

w = ["python" , "numpy" , "pandas"]

v = np.array(w)

In [39]:
v

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [40]:
np.char.upper(v)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [41]:
np.char.lower(v)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [42]:
np.char.title(v)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [43]:
#Que6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
result = np.char.join(' ', arr)
print(result)


['p y t h o n' 'n u m p y' 'p a n d a s']


In [44]:
#Que 7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.?

#Ans.7

a = np.array([[1,2],[1,6]])
b = np.array([[1,2],[1,6]])

In [45]:
a

array([[1, 2],
       [1, 6]])

In [46]:
b

array([[1, 2],
       [1, 6]])

In [47]:
Add = a+b

In [49]:
Add

array([[ 2,  4],
       [ 2, 12]])

In [50]:
sub = a-b

In [51]:
sub

array([[0, 0],
       [0, 0]])

In [52]:
multi = a*b

In [53]:
multi

array([[ 1,  4],
       [ 1, 36]])

In [54]:
division= a/b

In [55]:
division

array([[1., 1.],
       [1., 1.]])

In [56]:
#Que.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.?

d = np.eye(5)

In [57]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
z = np.diag(d)
z

array([1., 1., 1., 1., 1.])

In [59]:
#Que 9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.?

#Ans.

import numpy as np
def is_prime(n):
  if n <= 1:
    return False
  if n <= 3:
    return True
  if n % 2 == 0 or n % 3 == 0:
    return False
  i = 5
  while i * i <= n:
    if n % i == 0 or n % (i + 2) == 0:
      return False
    i = i + 6
  return True

r = np.random.randint(0,1001,(100))
r


array([483, 247, 189,  83, 457, 436,  12, 817, 741, 153, 229, 724, 997,
       189, 448, 669, 258, 738, 794, 369, 474, 884, 951, 213, 465, 936,
       383, 447, 925, 736, 489, 505, 263, 436, 373, 941,  18, 230, 226,
       737, 809, 366, 204, 549,   3, 498,  91,  64, 458, 483, 471, 249,
       473, 621,  87, 473, 380, 726, 901, 416, 863, 385, 384, 881, 983,
       545, 655, 512, 112, 298, 966, 879, 180, 124, 940, 203, 445, 189,
       455, 520, 645, 443,  68, 331,  54, 230, 421, 935, 751, 246, 815,
        81, 734, 810, 266, 105, 808, 660, 873, 293])

In [64]:
q = [num for num in r if is_prime(num)]
q

[83,
 457,
 229,
 997,
 383,
 263,
 373,
 941,
 809,
 3,
 863,
 881,
 983,
 443,
 331,
 421,
 751,
 293]

In [69]:
#Que 10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.?

#Ans.

import numpy as np
# Sample daily temperatures for a month (replace with actual data)
daily_temps = np.array([25, 26, 24, 28, 30, 29, 27,
                        26, 28, 29, 31, 30, 28,
                        27, 26, 25, 24, 23, 25,
                        27, 28, 29, 30, 31, 32,
                        30, 29, 28, 27, 26])

# Reshape the array to represent weeks (assuming 4 weeks in a month)
weekly_temps = daily_temps.reshape(5, 6)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temps, axis=1)

# Display weekly averages
print("Weekly Averages:", weekly_averages)

Weekly Averages: [27.         28.5        25.5        28.33333333 28.66666667]
